web:
    image: samnydahl/rapid-laravel:latest
    ports:
        - 8080:80
    volumes:
        - ./:/var/www
    links:
        - db
    stdin_open: true
    tty: true
db:
    image: mysql
    ports:
        - 33060:3306
    environment:
        MYSQL_DATABASE: dbname
        MYSQL_USER: username
        MYSQL_PASSWORD: p455w0rd
        MYSQL_ROOT_PASSWORD: example
